<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<script src="<?=$this->path('js/jquery.js')?>" type="text/javascript" charset="utf-8"></script>
	<script src="<?=$this->path('js/jquery.blockUI.js')?>" type="text/javascript" charset="utf-8"></script>
	<script src="<?=$this->path('js/jquery.tablesorter.js')?>" type="text/javascript" charset="utf-8"></script>
	<script src="<?=$this->path('js/jquery.selectboxes.js')?>" type="text/javascript" charset="utf-8"></script>
	<script src="<?=$this->path('js/sprintf.js')?>" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="<?=$this->path('styles/style.css')?>" />